### ISSUE TITLE
TestableHttpClientFactory doesn't assign BaseUri

### ISSUE THREAD

**Issue by Joshhua5** [testablehttpclient/TestableHttpClient#261]
Hey,

I have a simple problem, the HttpClient's will perform validation on a request to make sure it has a BaseUrl before reaching the TestableHttpHandler. 

Also, the CreateClient from the TestableHttpHandler doesn't set this BaseUri. 

Because of this, any request that uses relative uri's and the (typically) configured BaseUri, will fault.

However the BaseUri is pointless when intercepting the requests, so assigning it to any valid non-null value like "http://localhost" could be a fix. 

I could reproduce in unit-tests by changing anything to a relative Uri

**Comment by dnperfors** [comment]
Hi,
Thanks for reporting this issue.
If I understand you correctly, the problem is that the BaseUri is not set by default by the `CreateClient` methods from the TestableHttpHandler.
To be honest I never considered this and it has never been an issue for me, especially since your code needs to configure the BaseUri anyways.

The workaround would be to use the following code:
```C#
TestableHttpHandler handler = new();
HttpClient client = handler.CreateClient(x => x.BaseUri = new Uri("https://localhost"));
```
